name: fisher_front_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  path_provider: ^2.0.11
  html: ^0.15.0
  http: ^1.2.2
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  cupertino_icons: ^1.0.0


flutter:
  uses-material-design: true

assets:
  - assets/default.png
